# -*- coding: utf-8 -*-
"""KDM_icp8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MtQGmrKcpLh0xdxW3WD402hjBMf6IVQa
"""

!pip install textacy
import spacy
import textacy

# reading input files
file = open('/content/article.txt', 'r')
# loading en_core_web_sm model
nlp = spacy.load("en_core_web_sm")
doc = nlp(file.read())
print(doc)
file.close()

for token in doc:
    print(token.text, token.pos_, token.dep_)

tuples_list = []
#extracting triplet using textacy library
tuples = textacy.extract.subject_verb_object_triples(doc)
tuples_to_list = list(tuples)
if tuples_to_list != []:
    tuples_list.append(tuples_to_list)

print(tuples_list)